version: "3"
services:
       login-app:
           build: .
           ports:
             - "1337:1337"
           links:
             - mongo
       mongo:
             image: mongo
             volumes:
               - ./data:/data/db
             ports:
               - '27018:27017'

